// Generated by scripts/connector-bundle.mjs (runs in `pnpm build`). Do not edit by hand.
export const BUNDLED_CONNECTOR_VERSION = "1.2.0";
export const BUNDLED_CONNECTOR_SHA256 = "0ddf9b322e158505b9bab3b41040195f3d1d68dba53fc6f0ded5c23afae1caaf";
