/**
 * The credentials the register starts with: the table "Credentials and expiry"
 * in `operations/vps/docs/security.md` (written 2026-10-03 after the gap
 * audit). Names and places only, never a value. "Unknown" in the source means
 * nobody recorded an expiry, not that there is none, so an unknown expiry is
 * left empty with a note.
 *
 * Seeded only where the Cockpit setting `credentialSeed` is ticked (Partners in
 * Biz's own company: these rows describe PiB's servers and tokens, so no client
 * company ever gets them). Once there, by `seed_key`: a re-run adds nothing and
 * never overwrites what a person changed. Remove a row from the register with
 * `credential-record` (status retired), not by editing this list.
 */
import type { CredentialStatus, VerifyProvider } from "./credentials-model.js";

export interface SeedCredential {
  seedKey: string;
  name: string;
  system: string;
  livesIn: string;
  expiresAt: string | null;
  expiryNote: string | null;
  rotateHow: string;
  rotateHref: string | null;
  verifyWith: VerifyProvider | null;
  status: CredentialStatus;
  notes: string | null;
}

const GITHUB_TOKENS = "https://github.com/settings/personal-access-tokens";
const GITHUB_CLASSIC = "https://github.com/settings/tokens";

export const CREDENTIAL_SEED: SeedCredential[] = [
  {
    seedKey: "github-fine-grained-new",
    name: "GitHub fine-grained token for agents and Paperclip",
    system: "GitHub, owner Partners-in-Biz",
    livesIn: "PAR company secret GITHUB_TOKEN; ~paperclip/.git-credentials.d/Partners-in-Biz",
    expiresAt: null,
    expiryNote: "Set when the token is created, at most one year: record the date here once it exists. The daily expiry watch on the server warns at 30 and 7 days.",
    rotateHow: "Create a new fine-grained token (Contents and Pull requests only), then run swap-github-token.sh again.",
    rotateHref: GITHUB_TOKENS,
    verifyWith: "github",
    status: "active",
    notes: "Contents and Pull requests only. Every agent git push and PR call uses it.",
  },
  {
    seedKey: "github-fine-grained-v1",
    name: "GitHub fine-grained token v1 (old, burned)",
    system: "GitHub, user PMStander, scope Partners-in-Biz",
    livesIn: "~/gh_token, run logs of 2026-09-29, /tmp/par16-tok.json, company secret version 1",
    expiresAt: "2027-09-29",
    expiryNote: null,
    rotateHow: "Delete it in GitHub (fine-grained tokens).",
    rotateHref: GITHUB_TOKENS,
    verifyWith: null,
    status: "burned",
    notes: "Printed into two run logs: treat as burned. Valid until its expiry unless deleted.",
  },
  {
    seedKey: "github-classic-old",
    name: "GitHub classic token (old, burned)",
    system: "GitHub, user PMStander",
    livesIn: "Company secret version 2 (set 2026-09-30), ~/.git-credentials, ~/.bashrc, ~/GITHUB_TOKEN_VALUE, /tmp",
    expiresAt: null,
    expiryNote: "No expiry known.",
    rotateHow: "Delete it in GitHub after the swap (same day).",
    rotateHref: GITHUB_CLASSIC,
    verifyWith: null,
    status: "burned",
    notes: "Scopes admin:org, admin:enterprise, delete_repo, workflow, admin:repo_hook: the most powerful credential on the server.",
  },
  {
    seedKey: "github-connection-grants",
    name: "GitHub per-user connection grants (Paperclip for GitHub)",
    system: "GitHub app",
    livesIn: "Paperclip connection grants",
    expiresAt: null,
    expiryNote: "No expiry known.",
    rotateHow: "The owner re-consents. Check the organisation's pending permission request first.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "claude-subscription-login",
    name: "Claude subscription login for claude_local",
    system: "Anthropic",
    livesIn: "/home/paperclip/.claude/.credentials.json",
    expiresAt: null,
    expiryNote: "Unknown: the Claude client refreshes it.",
    rotateHow: "claude login as the paperclip user.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "The sanctioned subscription path.",
  },
  {
    seedKey: "claude-setup-token",
    name: "Claude setup-token CLAUDE_CODE_OAUTH_TOKEN",
    system: "Anthropic",
    livesIn: "13 files in /etc/hermes/profiles/ and the Hermes gateway environment",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Run harden-hermes-env.sh, then revoke it on the Claude side.",
    rotateHref: null,
    verifyWith: null,
    status: "burned",
    notes: "A subscription token must never be in Hermes (owner rule). It was readable by two groups.",
  },
  {
    seedKey: "nous-key",
    name: "Nous key for Hermes",
    system: "Nous Research",
    livesIn: "/home/paperclip/.hermes/auth.json",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Provider dashboard.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "Used by most Hermes agents. A spend cap at the provider is an open item.",
  },
  {
    seedKey: "xai-key",
    name: "xAI key for the Pip gateway",
    system: "xAI",
    livesIn: "/var/lib/hermes/.hermes/auth.json",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Provider dashboard.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "google-oauth-app",
    name: "Google OAuth app (Mailbox, SEO)",
    system: "Google Cloud",
    livesIn: "Paperclip company secrets",
    expiresAt: null,
    expiryNote: "App status is In production, External, unverified. Record the verification decision date when it is taken.",
    rotateHow: "Decide on verification in the Google Cloud console.",
    rotateHref: "https://console.cloud.google.com/apis/credentials/consent",
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "google-seo-service-account",
    name: "Google service account key for SEO",
    system: "Google Cloud",
    livesIn: "Company secret (setup-seo-google.sh)",
    expiresAt: null,
    expiryNote: "Service account keys do not expire.",
    rotateHow: "Create a new key, update the secret, delete the old key.",
    rotateHref: "https://console.cloud.google.com/iam-admin/serviceaccounts",
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "linkedin-cma",
    name: "LinkedIn app (Community Management API)",
    system: "LinkedIn",
    livesIn: "LinkedIn developer app; review pending",
    expiresAt: null,
    expiryNote: "Submitted 2026-10-01. The outcome arrives by email to the owner.",
    rotateHow: "Not applicable until approved. A plugin change is needed on approval.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "r2-backup-token",
    name: "Cloudflare R2 backup token",
    system: "Cloudflare",
    livesIn: "/root/pib-ops/rclone.conf",
    expiresAt: null,
    expiryNote: "No expiry and no IP filter, by design.",
    rotateHow: "Create a new token, then run setup-r2.sh.",
    rotateHref: "https://dash.cloudflare.com/profile/api-tokens",
    verifyWith: null,
    status: "active",
    notes: "Bucket pib-paperclip-backups.",
  },
  {
    seedKey: "r2-storage-token",
    name: "Cloudflare R2 storage token",
    system: "Cloudflare",
    livesIn: "Company secrets (setup-storage.sh)",
    expiresAt: null,
    expiryNote: "None set.",
    rotateHow: "Create a new token, then run setup-storage.sh.",
    rotateHref: "https://dash.cloudflare.com/profile/api-tokens",
    verifyWith: "cloudflare",
    status: "active",
    notes: "Buckets pib-media and pib-private.",
  },
  {
    seedKey: "typesafe-key",
    name: "TypeSafe API key (Jev)",
    system: "TypeSafe",
    livesIn: "Company secret",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Vendor dashboard.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "Spend caps are an open item.",
  },
  {
    seedKey: "resend-key",
    name: "Resend API key",
    system: "Resend",
    livesIn: "Company secret",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Vendor dashboard.",
    rotateHref: "https://resend.com/api-keys",
    verifyWith: "resend",
    status: "active",
    notes: "Spend caps are an open item.",
  },
  {
    seedKey: "pagespeed-key",
    name: "PageSpeed API key",
    system: "Google Cloud",
    livesIn: "Company secret",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Google Cloud console.",
    rotateHref: "https://console.cloud.google.com/apis/credentials",
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "telegram-alert-bot",
    name: "Telegram alert bot token",
    system: "Telegram",
    livesIn: "/root/pib-ops/notify.env (mode 600)",
    expiresAt: null,
    expiryNote: "None.",
    rotateHow: "BotFather /revoke, then run setup-notify.sh.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "Never given to an agent.",
  },
  {
    seedKey: "paperclip-board-token",
    name: "Paperclip board API token",
    system: "Paperclip",
    livesIn: "/home/paperclip/.paperclip/auth.json",
    expiresAt: null,
    expiryNote: "Unknown.",
    rotateHow: "Sign in again.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "Read by the ops scripts.",
  },
  {
    seedKey: "paperclip-master-key",
    name: "Paperclip master.key",
    system: "Paperclip",
    livesIn: "secrets/master.key (in the encrypted backup)",
    expiresAt: null,
    expiryNote: "None.",
    rotateHow: "Cannot be rotated casually: it opens every stored secret.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: null,
  },
  {
    seedKey: "backup-age-key",
    name: "Backup age private key",
    system: "age",
    livesIn: "The owner's Mac, ~/.config/pib-paperclip/backup-age-key.txt",
    expiresAt: null,
    expiryNote: "None.",
    rotateHow: "Make a new key pair and re-encrypt the backups.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "Custody in a password manager is unconfirmed: without this key no backup can be read. See the custody confirmations in Setup.",
  },
  {
    seedKey: "root-ssh-keys",
    name: "Root SSH keys",
    system: "The Paperclip server",
    livesIn: "Two keys, both the owner's",
    expiresAt: null,
    expiryNote: "None.",
    rotateHow: "Add a deputy's key and remove a lost one.",
    rotateHref: null,
    verifyWith: null,
    status: "active",
    notes: "A single point of failure while both are the owner's.",
  },
  {
    seedKey: "covalonic-vendor-keys",
    name: "Covalonic vendor keys (Firebase Admin, Stripe, SendGrid, Vision, VAPID, APNs)",
    system: "Client vendors",
    livesIn: "Tracked in PMStander/covalonic, main and development",
    expiresAt: null,
    expiryNote: "Not applicable.",
    rotateHow: "Rotate in each vendor console, then remove the files from the repository. Removing them does not remove them from history.",
    rotateHref: null,
    verifyWith: null,
    status: "burned",
    notes: "Treat as exposed.",
  },
];
