// Embeds docs/data-processing-register.md in the worker: writes src/register-doc.generated.ts so the CRM can seed its
// data-processing register table from the docs file without reading the disk at run time.
//
//   node scripts/register-doc.mjs
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const DOC = fileURLToPath(new URL("../docs/data-processing-register.md", import.meta.url));
const GENERATED = fileURLToPath(new URL("../src/register-doc.generated.ts", import.meta.url));

export function renderRegisterDoc(markdown) {
  return `// Generated by scripts/register-doc.mjs (runs in \`pnpm build\`) from docs/data-processing-register.md. Do not edit by hand.
export const REGISTER_DOC = ${JSON.stringify(markdown)};
`;
}

export async function writeRegisterDoc() {
  const markdown = await readFile(DOC, "utf8");
  await writeFile(GENERATED, renderRegisterDoc(markdown));
  return { bytes: markdown.length };
}

const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) writeRegisterDoc().then((r) => console.log(`Register doc embedded (${r.bytes} bytes)`));
